"""Constants for the TeslaMate MQTT integration."""

CONF_TOPIC_ROOT = "topic_root"
DOMAIN = "teslamate_mqtt"

TOPIC_BATTERY_LEVEL = "battery_level"
TOPIC_CENTER_DISPLAY_STATE = "center_display_state"
TOPIC_CHARGE_ENERGY_ADDED = "charge_energy_added"
TOPIC_CHARGE_LIMIT_SOC = "charge_limit_soc"
TOPIC_CHARGE_CURRENT_REQUEST = "charge_current_request"
TOPIC_CHARGE_CURRENT_REQUEST_MAX = "charge_current_request_max"
TOPIC_DISPLAY_NAME = "display_name"
TOPIC_DOORS_OPEN = "doors_open"
TOPIC_LATITUDE = "latitude"
TOPIC_LONGITUDE = "longitude"
TOPIC_MODEL = "model"
TOPIC_TRIM_BADGING = "trim_badging"
TOPIC_VERSION = "version"
