"""Constants for the TeslaMate MQTT integration."""

CONF_TOPIC_ROOT = "topic_root"
DOMAIN = "teslamate_mqtt"

TOPIC_BATTERY_LEVEL = "battery_level"
TOPIC_CENTER_DISPLAY_STATE = "center_display_state"
TOPIC_CHARGE_PORT_DOOR_OPEN = "charge_port_door_open"
TOPIC_CHARGER_ACTUAL_CURRENT = "charger_actual_current"
TOPIC_CHARGE_ENERGY_ADDED = "charge_energy_added"
TOPIC_CHARGE_LIMIT_SOC = "charge_limit_soc"
TOPIC_CHARGE_CURRENT_REQUEST = "charge_current_request"
TOPIC_CHARGE_CURRENT_REQUEST_MAX = "charge_current_request_max"
TOPIC_CHARGING_STATE = "charging_state"
TOPIC_DISPLAY_NAME = "display_name"
TOPIC_DOORS_OPEN = "doors_open"
TOPIC_DRIVER_FRONT_DOOR_OPEN = "driver_front_door_open"
TOPIC_DRIVER_REAR_DOOR_OPEN = "driver_rear_door_open"
TOPIC_CHARGER_PHASES = "charger_phases"
TOPIC_CHARGER_POWER = "charger_power"
TOPIC_CHARGER_VOLTAGE = "charger_voltage"
TOPIC_CLIMATE_KEEPER_MODE = "climate_keeper_mode"
TOPIC_LATITUDE = "latitude"
TOPIC_LONGITUDE = "longitude"
TOPIC_MODEL = "model"
TOPIC_PASSENGER_FRONT_DOOR_OPEN = "passenger_front_door_open"
TOPIC_PASSENGER_REAR_DOOR_OPEN = "passenger_rear_door_open"
TOPIC_TRIM_BADGING = "trim_badging"
TOPIC_VERSION = "version"
